name: ThirdPlugin
version: ${project.version}
main: me.kc.thirdplugin.ThirdPlugin
api-version: 1.16
authors: [kc, ethan]
description: Plugin3
commands:
    rise:
      description: teleports player up 10 blocks.
      usage: /<command>
    bind:
      description: bind a command to the held object
    setjoinmessage:
      description: Sets the join message.
      usage: /<command> <field> <string>